=== bbengamin/finalTask4/WebContent/xml/input.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--  XML schema -->

<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://localhost:8080/SummaryTask4/xml" 
	xmlns:tns="http://localhost:8080/SummaryTask4/xml">

	<xsd:element name="Test">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element name="Question" 
					type="tns:Question" maxOccurs="unbounded"/>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>

	<xsd:complexType name="Question">
		<xsd:sequence>
			<xsd:element name="QuestionText" type="xsd:string" />
			<xsd:sequence>
				<xsd:element name="Answer" type="tns:Answer" maxOccurs="4"/>
			</xsd:sequence>			
		</xsd:sequence>
	</xsd:complexType>

	<xsd:complexType name="Answer" mixed="true">
		<xsd:attribute name="correct" type="xsd:boolean" default="false" />		
	</xsd:complexType>
</xsd:schema>

=== bbengamin/finalTask4/xml/questions.xml
<?xml version="1.0" encoding="UTF-8"?>

<st4:Test xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xmlns:st4="http://localhost:8080/SummaryTask4/xml"
	xsi:schemaLocation="http://localhost:8080/SummaryTask4/xml http://localhost:8080/SummaryTask4/xml/input.xsd">
	<Question>
		<QuestionText>Сколько всего было крестражей?</QuestionText>
		<Answer>5</Answer>
		<Answer>10</Answer>
		<Answer correct="true">7</Answer>
		<Answer>2</Answer>
	</Question>
	<Question>
		<QuestionText>Как звали змею «Того-Кого-Нельзя-Называть»</QuestionText>
		<Answer correct="true">Нагайна</Answer>
		<Answer>Каа</Answer>
		<Answer>Просто змея</Answer>
	</Question>
	<Question>
		<QuestionText>Каким из даров смерти владел отец Гарри?</QuestionText>
		<Answer>Палочка</Answer>
		<Answer correct="true">Мантия невидимка</Answer>
		<Answer>Воскрешающий камень</Answer>
	</Question>
</st4:Test>

=== bbengamin/finalTask4/xml/input.xml
<?xml version="1.0" encoding="UTF-8"?>

<st4:Test xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xmlns:st4="http://localhost:8080/SummaryTask4/xml"
	xsi:schemaLocation="http://localhost:8080/SummaryTask4/xml http://localhost:8080/SummaryTask4/xml/input.xsd">
	<Question>
		<QuestionText>Какое сейчас время суток?</QuestionText>
		<Answer>День</Answer>
		<Answer correct="true">Ночь</Answer>
	</Question>
	<Question>
		<QuestionText>Сколь будет 12 - 7</QuestionText>
		<Answer>8</Answer>
		<Answer>очень много</Answer>
		<Answer correct="true">5</Answer>
		<Answer correct="true">пять</Answer>
	</Question>
	<Question>
		<QuestionText>Добро всегда побеждает</QuestionText>
		<Answer>ночные кошмары</Answer>
		<Answer correct="true">зло</Answer>
		<Answer>простуду</Answer>
	</Question>
</st4:Test>

=== bbengamin/finalTask4/xml/questions1.xml
<?xml version="1.0" encoding="UTF-8"?>

<st4:Test xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xmlns:st4="http://localhost:8080/SummaryTask4/xml"
	xsi:schemaLocation="http://localhost:8080/SummaryTask4/xml http://localhost:8080/SummaryTask4/xml/input.xsd">
	<Question>
		<QuestionText>Как звучит традиционное прощание джедаев</QuestionText>
		<Answer>Удачи)</Answer>
		<Answer correct="true">Да прибудет с тобой сила</Answer>
		<Answer correct="true">May the Forth be with you</Answer>
		<Answer>Пока пока)</Answer>
	</Question>
	<Question>
		<QuestionText>Как звали астрособота Энакина</QuestionText>
		<Answer correct="true">R2-D2</Answer>
		<Answer>Кастрюля</Answer> 
		<Answer>Пылесос</Answer>
	</Question>
</st4:Test>
